Sylvano33/BETFRIENDS

app/models/user.rb, db/migrate/20180522091438_add_username_to_users.rb, db/schema.rb
=> validates and username magration done

app/models/bet.rb, db/migrate/20180521163045_create_bets.rb, db/schema.rb, test/models/bet_test.rb
completed bet model, also modified the DB schema.
=> completed bet model

app/models/bet.rb, app/models/user.rb, app/models/user_bet.rb, db/migrate/20180521163045_create_bets.rb, db/migrate/20180522121327_create_user_bets.rb, db/schema.rb, db/seeds.rb, test/models/user_bet_test.rb
=> Scope and relations

db/seeds.rb
=> seed done 2

app/controllers/bets_controller.rb
=> mailer  bug fixed

app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb
=> navbar fixed in mobile format

app/views/bets/new.html.erb, app/views/shared/_flashes.html.erb
=> asterisque enlevée du new

app/javascript/packs/application.js, app/views/bet_mailer/enddate.html.erb, app/views/bets/new.html.erb, app/views/layouts/application.html.erb, package.json, yarn.lock
Couldn't add pink color to datapicker :s 
> Day starts from Monday ( not sunday anymore )
`locale: {
firstDayOfWeek: 1
}`
> Default language set to French
`flatpickr(element, {
"locale": French 
});
`
=> Flat picker

app/views/bets/index.html.erb, app/views/bets/show.html.erb
=> User buttons

app/javascript/packs/application.js
Date picker now correctly displays : 
> good date format
> FR language
> Pickable day ( starting from today only )
=> DatePickr Bug FIXED

app/models/user.rb, app/views/bets/index.html.erb
=> footer bug fixed

app/assets/stylesheets/pages/_index.scss, app/views/bets/index.html.erb
=> bug color and align done

app/assets/stylesheets/pages/_index.scss, app/assets/stylesheets/pages/_show.scss, app/controllers/bets_controller.rb, app/views/bets/show.html.erb, app/views/layouts/application.html.erb, app/views/pages/home.html.erb
=> bug double bet fixed

app/assets/stylesheets/pages/_index.scss, app/views/bets/index.html.erb
=> added orange value to rate

app/assets/stylesheets/pages/_index.scss, app/views/bets/index.html.erb, app/views/bets/new.html.erb
=> affichage status

app/assets/stylesheets/pages/_index.scss, app/views/bets/index.html.erb
fond gris sur pending et accepted
=> fond gris sur pending et accepted

Gemfile, Gemfile.lock, app/controllers/bets_controller.rb, app/javascript/components/flatpickr.js, app/javascript/packs/application.js, app/views/bets/index.html.erb, config/application.rb
Removed Flatpickr from app.js, created a component instead. Date is now properly displayed on Bet#index <3
=> Final ver of datepicker, correct date in bet#index

app/assets/stylesheets/pages/_index.scss, app/views/bets/index.html.erb
=> fond gris enlevé

public/404.html, public/500.html
=> 500 404 added

app/assets/stylesheets/pages/_index.scss
=> cases index ok

app/views/bets/show.html.erb
=> petites choses sur show

app/views/bets/show.html.erb
=> countdown chez receveur

app/assets/stylesheets/pages/_index.scss, app/views/bets/show.html.erb
=> quelques modif
